os:
  - osx
language: swift
sudo: required
osx_image: xcode10.3
xcode_workspace: ThreeDCardView.xcworkspace
xcode_scheme: ThreeDCardView_ExampleTests
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone 8
before_install:
  - export LANG=en_US.UTF-8
  - brew update
  - brew unlink xctool
  - brew install xctool
  - brew link xctool
  - cd Example
  - pod install
notifications:
  email:
    on_success: never
    on_failure: never
