osx_image: xcode11.7
language: swift
os: osx
xcode_workspace: ThreeDCardView.xcworkspace
xcode_scheme: TravisCITest
xcode_destination: platform=iOS Simulator,OS=13.7,name=iPhone 8
before_install:
- pod install
