os: osx
osx_image: xcode10.1
language: swift
script: xcodebuild clean build test  -workspace Example/ThreeDCardView.xcworkspace -scheme ThreeDCardView-Example -sdk iphonesimulator -destination “platform=iOS Simulator,OS=12.1,name=iPhone 6” ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
